graph [

  node [ id 0 label "1"  membership "1,1,1" ]
  node [ id 1 label "2"  membership "1,1,1" ]
  node [ id 2 label "3"  membership "1,1,1" ]
  node [ id 3 label "4"  membership "0,1,0" ]
  node [ id 4 label "5"  membership "0,1,0" ]
  node [ id 5 label "6"  membership "0,1,0" ]
  node [ id 6 label "7"  membership "0,1,0" ]
  node [ id 7 label "8"  membership "1,0,0" ]
  node [ id 8 label "9"  membership "1,0,0" ]
  node [ id 9 label "10" membership "1,0,0" ]

  edge [ source 0 target 1 ]
  edge [ source 0 target 2 ]
  edge [ source 0 target 3 ]
  edge [ source 0 target 4 ]
  edge [ source 0 target 5 ]
  edge [ source 0 target 6 ]
  edge [ source 0 target 7 ]
  edge [ source 0 target 8 ]
  edge [ source 0 target 9 ]

  edge [ source 1 target 2 ]
  edge [ source 1 target 3 ]
  edge [ source 1 target 4 ]
  edge [ source 1 target 5 ]
  edge [ source 1 target 6 ]
  edge [ source 1 target 7 ]
  edge [ source 1 target 8 ]
  edge [ source 1 target 9 ]

  edge [ source 2 target 3 ]
  edge [ source 2 target 4 ]
  edge [ source 2 target 5 ]
  edge [ source 2 target 6 ]
  edge [ source 2 target 7 ]
  edge [ source 2 target 8 ]
  edge [ source 2 target 9 ]

  edge [ source 3 target 4 ]
  edge [ source 3 target 5 ]
  edge [ source 3 target 6 ]
  edge [ source 4 target 5 ]
  edge [ source 4 target 6 ]
  edge [ source 5 target 6 ]

  edge [ source 7 target 8 ]
  edge [ source 7 target 9 ]
  edge [ source 8 target 9 ]

]
